### ISSUE TITLE
 Initialize Backend Config with TypeScript, Express, and TypeORM

### ISSUE THREAD

**Issue by KevinLatino** [StarShopCr/StarShop-Backend#1]
Set up the backend project with TypeScript, Express, and TypeORM to ensure a robust, scalable, and type-safe application structure. The configuration should include TypeORM integration for handling entities and migrations.

**Comment by Villarley** [comment]
Hi sir! I want to work on this!

**Comment by KevinLatino** [comment]
Got it! Task assigned to you. Let me know if you need further clarification or additional support! 😊

**Comment by KevinLatino** [comment]
How is it going?

**Comment by KevinLatino** [comment]
Chief, if you don´t aswer i will reassign
