### ISSUE TITLE
[BK]: Create User Entity and CRUD APIs

### ISSUE THREAD

**Issue by KevinLatino** [StarShopCr/StarShop-Backend#11]
> [!IMPORTANT]  
  Before applying, please read the [Contributors Guide](https://github.com/StarShopCr/contributors-guide). Following the guide increases your chances of being assigned to this task.  

**Description**: Define the `User` entity for the `users` table and implement fully typed CRUD APIs.

### Entity Definition
```typescript
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn } from 'typeorm';

@Entity('users')
export class User {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ unique: true })
  walletAddress: string;

  @Column({ nullable: true })
  name: string;

  @Column({ nullable: true })
  email: string;

  @Column()
  role: 'buyer' | 'seller' | 'admin';

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
```

### Tasks
1. Create the `User` entity in TypeORM.
2. Add CRUD operations: Create, Read, Update, Delete users.
3. Use DTOs for strong typing in API payloads.
4. Write comprehensive unit and integration tests for APIs.

### Acceptance Criteria
- Fully functional APIs for CRUD operations.
- APIs documented in Swagger/OpenAPI.
- All tests pass with >80% code coverage.

**Comment by coxmars** [comment]
Hi @KevinLatino, I'm a software developer with 2+ years of experience and I have worked with backend technologies such as Cairo, Java, C# and frontend with React, NextJS, JS/TS. Also, I'm a member of the Dojo Coding community here in CR and I have made contributions in Cairo VM Go, Cairo VM TS, Cairo Lints etc. Likewise, I’m a Cairo developer working in ByteBuildersLabs creating on-chain games using the Dojo framework.

This is my approach:

1- I will review the project structure to place the entities and other parts as expected.
2- I’m going to use the code structure/best practices implemented among the project codebase to continue the standard
3- I will implement the crud operations and apply validations where needed.
4- I'm going to add the unit tests and integration tests passing with > 80% code coverage.
5- Finally, I’ll test all changes to validate all is working as expected.

ET: 3 days

**Comment by Kachimercy1** [comment]
I'd be happy to do this.

**Comment by oluchicharity** [comment]
I'm Oluchi, a backend and smart contract developer passionate about building secure, scalable, and well-architected applications. I specialize in Web3 integrations, authentication systems, and API development. I enjoy tackling challenging projects and writing clean, maintainable code that drives real-world solutions. i would love to have a go at this issue!

**Comment by Supa-mega** [comment]
Mind if I try this one?

**Comment by anonfedora** [comment]
I'm Anonfedora, a full stack Blockchain developer (Backend heavy)...
1. Define the User entity in TypeORM with appropriate decorators and validations based on the provided schema. 
2. Create DTOs for user-related operations to ensure type safety for request and response payloads. 
3. Implement the CRUD APIs using a controller-service-repository pattern, leveraging TypeORM's repository methods. 
4. Write unit tests for services and controllers, and integration tests for the API endpoints to ensure functionality. 
5. Ensure >80% test coverage using tools like Jest, and validate the APIs with Postman or similar tools.
ETA: 72 hours

**Comment by Shukazuby** [comment]
My name is Zubaidat, a backend developer with experience in building scalable and secure web applications using Node.js(Typescript). I have hands-on experience working with TypeORM, RESTful APIs, and test-driven development.

Plan to Solve the Issue:

I will create the User entity using TypeORM, ensuring it adheres to the required database schema. CRUD operations will be implemented with proper input validation, leveraging DTOs for strong typing in API payloads. Comprehensive unit and integration tests will be written to verify the accuracy and reliability of the APIs. Best practices, including modularity and code readability, will be followed throughout the development process.

ETA:
I estimate completing the task in 4 days, including development, testing, and documentation.

Thank you

**Comment by EmmanuelAR** [comment]
Hello team Im Emmanuel Aguero from Costa Rica, Dojo coding member and Go Stark Me team member.
I will like to work on this issue, i will follow the instructions to create the user entity

let me know!

**Comment by Bosun-Josh121** [comment]
I am applying to this issue via OnlyDust platform.

My background and how it can be leveraged:

software engineering background, backend & smart contract dev with contribution to similar tasks(https://app.onlydust.com/u/Bosun-Josh121) looking to make first contribution on this project

How I plan on tackling this issue
I will define the User entity with fields for id, walletAddress, name, email, role, createdAt, and updatedAt, ensuring constraints like uniqueness and optional fields are correctly set.
I will create fully typed APIs for:
Create: Adding new users with DTOs to ensure strong typing.
Read: Fetching users by ID and querying lists with filters.
Update: Modifing user details while maintaining validation.
Delete: Safely removing users.
I will write comprehensive unit and integrtion tests, ensuring >80% code coverage stated in criteria.
work on feedback & recommendation ensuring contact. Can deliver within a day upon assignment

**Comment by ShantelPeters** [comment]
May I take care of this?

**Comment by zleypner** [comment]
Hi! I’m Anwar a Software Developer with +3 years of experience, and I would love 
make a contribution to this project and contribute to the project's success. 

I will create the User entity for the users table in TypeORM and implement fully typed CRUD APIs. This includes defining the User entity with properties like id, walletAddress, name, email, role, createdAt, and updatedAt. I'll implement the CRUD operations with strong typing using DTOs and ensure the APIs are documented in Swagger/OpenAPI. I will also write unit and integration tests to achieve over 80% code coverage. I estimate completing this task in 2-3 days.

**Comment by Amarjeet325** [comment]
Is it okay if I tackle this?

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Michaelkingsdev** [comment]
I can handle this particular task.

**Comment by psychemist** [comment]
Hi. I am a fullstack web developer and a recent alumni of Web3Bridge, the largest and most sought after blockchain developer community in Africa. I have extensive backend experience building user authentication systems for e-commerce and education website backends. I am a new contributor to OnlyDust and would love to take on this task to increase my knowledge base and contribute to open source projects. I am skilled in C, HTML/CSS, JavaScript, Python, and Solidity.

To solve this task, i would:

- Define the User entity using TypeORM with properties like id, walletAddress, name, email, role, createdAt, and updatedAt in the users table.
- Next, I will implement methods for creating, reading, updating, and deleting users with proper validations in the UserService class.
- Then, I will define DTOs (Data Transfer Objects) for strong typing of the API payloads, ensuring proper structure and validation for input data.
- Afterward, I will implement API endpoints for CRUD operations (e.g., /users, /users/:id) with the relevant HTTP methods (GET, POST, PUT, DELETE).
- Lastly, i will write unit and integration tests for the APIs using a testing framework like Jest to ensure all CRUD operations work as expected.


I aim to complete this task within 6 hours after being assigned and setting up my development environment.

Thank you for the opportunity and I look forward to working with you.

**Comment by gregemax** [comment]
Can I take this from here? I have experience in backend development with TypeScript and TypeORM. I’m confident in defining the User entity, implementing CRUD operations with strong typing via DTOs, and documenting the APIs in Swagger/OpenAPI. I’ll also ensure comprehensive test coverage above 80%

**Comment by Guzbyte-tech** [comment]
Hi @KevinLatino , I am a highly experienced backend developer with expertise in building robust, scalable systems and delivering fully functional APIs. My recent foray into Node.js and TypeScript has been exciting, allowing me to leverage modern development practices like strong typing, decorators, and efficient ORM tools such as TypeORM. My experience across various backend technologies equips me to approach this task with confidence.

To tackle this task, I will:

- Define the User entity using TypeORM, ensuring it aligns with database schema requirements.
- Implement fully typed CRUD APIs using DTOs to maintain strong type safety across API payloads.
- Write comprehensive unit and integration tests to ensure functionality, edge-case handling, and code reliability.
- Maintain clean, well-structured code that adheres to industry standards for scalability and readability.

Estimated Completion Time (ETA):
I estimate completing this task in 3 days, which includes development, testing, and thorough review of the code to ensure all acceptance criteria are met.

**Comment by 1nonlypiece** [comment]
I'd love to work on this!

**Comment by KevinLatino** [comment]
@Guzbyte-tech Task assigned to you. Let me know if you need further clarification or additional support!😊

Here is our telegram group, please join https://t.me/starshopcr
