### ISSUE TITLE
[BK]: Add User Authentication (API)

### ISSUE THREAD

**Issue by KevinLatino** [StarShopCr/StarShop-Backend#12]
> [!IMPORTANT]  
Before applying, please read the [Contributors Guide](https://github.com/StarShopCr/contributors-guide). Following the guide increases your chances of being assigned to this task.  

# Description
Implement an authentication mechanism for users, allowing login via wallet address and returning a signed JWT.

# Tasks
1. Create an `authenticateUser` service method in the `UserService`.
2. Add the `POST /auth/login` endpoint to accept wallet address and return a signed JWT token.
3. Write middleware to validate the token and attach user details to the request.
4. Document authentication flow in Swagger/OpenAPI.

# Example Service Implementation
```typescript
import jwt from 'jsonwebtoken';
import { User } from '../entities/User';
import { AppDataSource } from '../data-source';

const SECRET_KEY = process.env.JWT_SECRET || 'defaultSecret';

class AuthService {
  static async authenticate(walletAddress: string): Promise<string> {
    const userRepo = AppDataSource.getRepository(User);
    const user = await userRepo.findOne({ where: { walletAddress } });

    if (!user) {
      throw new Error('User not found');
    }

    return jwt.sign({ id: user.id, role: user.role }, SECRET_KEY, { expiresIn: '1h' });
  }
}
```

# Acceptance Criteria
- `POST /auth/login` accepts wallet address and returns a JWT token.
- Middleware validates the token and attaches user details to the request object.
- All tests pass with >80% code coverage.

---

**Comment by Supa-mega** [comment]
I'd be happy to do this.

**Comment by Shukazuby** [comment]
I am Zubaidat, a backend developer with expertise in building secure and scalable APIs. I have experience with authentication mechanisms, JWT implementation, and API documentation using Swagger/OpenAPI.

Plan to Solve the Issue:

I will implement an authentication system enabling users to log in via their wallet address. The solution will include creating the authenticateUser service method in UserService, a POST /auth/login endpoint to handle login requests, and middleware to validate the JWT and attach user details to the request object. I will follow security practices, such as securely signing tokens and validating payloads. The entire authentication flow will be documented in Swagger/OpenAPI for clarity and ease of use.

ETA:
I estimate completing this task within 2 days, including development, testing, and documentation.

Thank you

**Comment by RajeshRk18** [comment]
I am a backend developer having proficiency in Typescript, Rust and Python. I have experience implementing complex auth mechanisms such as oauth, 2FA, and SSO. So, I have the confidence and ability to implement JWT based authentication.

Here is how I planned to approach it!

**Create authenticateUser Service:**
Implement authenticateUser in AuthService to generate a JWT token for users authenticated via wallet address.

**Add POST /auth/login Endpoint:**
Create a new route (/auth/login) to accept wallet address, authenticate the user, and return the JWT token.

**Middleware for JWT Validation:**
Write middleware to validate the JWT token and attach the authenticated user details to the request.

**Document Authentication Flow:**
Use Swagger/OpenAPI to describe the POST /auth/login endpoint, request body, and response schema.

And finally,
**Test Coverage:**
Write unit tests and integration tests to ensure >80% code coverage.

ETA: 2days

**Comment by ShantelPeters** [comment]
I’d like to work on this.

**Comment by Amarjeet325** [comment]
Is it okay if I tackle this?

**Comment by ooochoche** [comment]
I am a blockchain developer and I have gone through the description and the required tasks to be completed, and I can make sure all accepted criteria are met

**Comment by sonkeydotcom** [comment]
Hello, can I take this. I plan to implement a service to verify wallet addresses, generate a signed JWT, create the /auth/login endpoint, and write middleware to validate tokens and attach user details. Estimated completion: 2 days.

**Comment by Michaelkingsdev** [comment]
I can handle this particular task.

**Comment by Michaelkingsdev** [comment]
I can handle this particular task.

**Comment by od-hunter** [comment]
Hi, please can I be assigned this please? This would be my first time contributing to this project and I would love to be the given the opportunity to contribute. I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo.

To solve this issue, I’ll take the following steps:
1.⁠ ⁠I’ll create an authenticate method in UserService to check if a user exists based on their wallet address and generate a signed JWT if valid. Then I’ll use jsonwebtoken to create the token with user data (ID, role) and set an expiration time.
2.⁠ ⁠⁠I’ll implement a POST /auth/login route that accepts a wallet address, calls the authenticate method, and returns a signed JWT to the user.
3.⁠ ⁠⁠Next, I’ll create the middleware (sessionMiddleware) that extracts the token from the Authorization header, verifies it using jsonwebtoken, and attaches the decoded user details (id, role) to the request object.
4.⁠ ⁠Next, I’ll use the middleware on protected routes to ensure authentication by validating the JWT token before granting access.
5.⁠ ⁠⁠Lastly, I’ll write unit tests to ensure the login endpoint generates and returns a valid JWT and the middleware correctly validates the token and attaches user data to the request.

ETA: 3 days
Kindly assign me please, I’m ready to work

**Comment by psychemist** [comment]
Hi. I am a fullstack web developer and a recent alumni of Web3Bridge, the largest and most sought after blockchain developer community in Africa. I have extensive backend experience building user authenticatin systems for e-commerce and education websites. I am a new contributor to OnlyDust and would love to take on this task to increase my knowledge base and contribute to open source projects.

I would solve this task by:
1. Create an `authenticateUser` service method in the UserService class.
2. Implement an `/auth/login` API endpoint that receives a post request containing a wallet address and returns a signed JWT token.
3. Write functional middleware that validates the generated token and attaches user details to the request.
4. Add good documentation that explains the authentication flow in Swagger/OpenAPI.

I aim to complete this task within 6 hours after being assigned and setting up my development environment.

Thank you for the opportunity and I look forward to working with you.

**Comment by gregemax** [comment]
Mind if I take this issue? I have experience in backend development with TypeScript, JWT-based authentication, and middleware implementation. I can deliver the required authentication mechanism, ensure token validation, and document the flow in Swagger/OpenAPI. I’ll also maintain test coverage above 80%.

**Comment by mimisavage** [comment]
Can I start working on this?

**Comment by Guzbyte-tech** [comment]
Hi @KevinLatino, I am a backend/Blockchain developer with experience building secure and efficient APIs, with a strong focus on authentication and user management systems. My expertise in backend development and recent hands-on experience with modern tools like Node.js, TypeScript, and TypeORM position me well to implement this feature with security and reliability as top priorities.

To implement the authentication mechanism, I will:

1. Create a secure authenticateUser service method to validate the wallet address and return a signed JWT token.
2. Add the POST /auth/login endpoint to handle login requests, ensuring proper input validation and error handling.
3. Write a robust middleware to validate the token and attach user details to the request object for downstream use.
4. Document the entire authentication flow in Swagger/OpenAPI, including the token validation middleware.
5. Ensure >80% code coverage with well-structured unit and integration tests, simulating both success and failure scenarios.

Estimated Completion Time (ETA): 3 days

**Comment by Nityam573** [comment]
Can I be assigned to this?

**Comment by 1nonlypiece** [comment]
Can I be assigned to this?

**Comment by 3th-Enjay** [comment]
I’d like to resolve this. I have experience doing this

**Comment by Villarley** [comment]
hey @zleypner 
Task assigned to you. Let me know if you need further clarification or additional support!😊

Here is our telegram group, please join https://t.me/starshopcr

**Comment by zleypner** [comment]
Hi @Villarley,
Thanks for assigning the task to me! I’ll will send a drat PR asap. 

I’ve joined the Telegram group as well!
