### ISSUE TITLE
[BK]: Create ProductType, ProductVariant, and Product Entities and APIs

### ISSUE THREAD

**Issue by KevinLatino** [StarShopCr/StarShop-Backend#14]
> [!IMPORTANT]  
  Before applying, please read the [Contributors Guide](https://github.com/StarShopCr/contributors-guide). Following the guide increases your chances of being assigned to this task.  

  # Description
  Implement `ProductType`, `ProductVariant`, and `Product` entities and their associated CRUD APIs.

  # Entity Definitions

  ## ProductType
  ```typescript
  import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn } from 'typeorm';

  @Entity('product_types')
  export class ProductType {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @Column({ type: 'text', nullable: true })
    description: string;

    @CreateDateColumn()
    createdAt: Date;
  }
  ```

  ## Product
  ```typescript
  import { Entity, PrimaryGeneratedColumn, Column, ManyToOne, CreateDateColumn } from 'typeorm';
  import { ProductType } from './ProductType';

  @Entity('products')
  export class Product {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @Column({ type: 'text', nullable: true })
    description: string;

    @ManyToOne(() => ProductType)
    productType: ProductType;

    @CreateDateColumn()
    createdAt: Date;
  }
  ```

  ## ProductVariant
  ```typescript
  import { Entity, PrimaryGeneratedColumn, Column, ManyToOne, CreateDateColumn } from 'typeorm';
  import { Product } from './Product';

  @Entity('product_variants')
  export class ProductVariant {
    @PrimaryGeneratedColumn()
    id: number;

    @ManyToOne(() => Product)
    product: Product;

    @Column()
    sku: string;

    @Column('decimal')
    price: number;

    @Column('int')
    stock: number;

    @CreateDateColumn()
    createdAt: Date;
  }
  ```

  # Tasks
  1. Define entities: `ProductType`, `Product`, and `ProductVariant`.
  2. Create fully functional CRUD APIs for each entity.
  3. Write comprehensive unit and integration tests.

  # Acceptance Criteria
  - APIs for CRUD operations work seamlessly.
  - Relationships between entities are properly enforced.
  - Test coverage >80%.

---

**Comment by anonfedora** [comment]
I'm Anonfedora, a full stack Blockchain developer (Backend heavy)...
1. Define the ProductType, Product, and ProductVariant entities with proper TypeORM relationships and validations. 
2. Create DTOs for each entity to ensure strong typing for API requests and responses. 
3. Build CRUD APIs for each entity, ensuring relationships like ManyToOne are correctly handled in the services. 
4. Write unit tests for services and controllers, and integration tests for the CRUD APIs to verify functionality and relationships. 
5. Ensure >80% test coverage using Jest and validate everything with Postman or Swagger. 
ETA: 80 hours

**Comment by anonfedora** [comment]
I'm Anonfedora, a full stack Blockchain developer (Backend heavy)...
1. Define the ProductType, Product, and ProductVariant entities with proper TypeORM relationships and validations. 
2. Create DTOs for each entity to ensure strong typing for API requests and responses. 
3. Build CRUD APIs for each entity, ensuring relationships like ManyToOne are correctly handled in the services. 
4. Write unit tests for services and controllers, and integration tests for the CRUD APIs to verify functionality and relationships. 
5. Ensure >80% test coverage using Jest and validate everything with Postman or Swagger. 
ETA: 80 hours

**Comment by Supa-mega** [comment]
Is this issue still available?

**Comment by jimenezz22** [comment]
Hi, I'd love to contribute to this issue! I'm part of the Dojo Coding community and have experience contributing to various open-source projects in OnlyDust and I manage a full-stack developer profile. 

### My Approach:

1. **Entity Definitions**
    - Use the provided `ProductType`, `Product`, and `ProductVariant` entity definitions to ensure consistency with the existing codebase.
    - Validate relationships between entities (`ProductType` → `Product` → `ProductVariant`) using TypeORM decorators.
2. **CRUD APIs**
    - Implement RESTful endpoints for each entity (`ProductType`, `Product`, `ProductVariant`) covering create, read, update, and delete operations.
    - Leverage TypeORM repository methods to handle database interactions efficiently.
3. **Testing**
    - Write unit tests for the service methods handling CRUD operations.
    - Create integration tests to validate API functionality and enforce relationships between entities.
    - Ensure test coverage exceeds the required 80%

ETA: 3 days maximum in the worst case scenario.

**Comment by Shukazuby** [comment]
I am Zubaidat, a backend developer with strong experience in TypeORM and building scalable APIs.

How I intend to Solve the Issue:
I will define the ProductType, Product, and ProductVariant entities in TypeORM and implement fully functional CRUD APIs for each. Additionally, I will write comprehensive unit and integration tests to ensure the APIs perform as expected and are reliable.

ETA:
I estimate completing this task in 3 days, including development, testing, and documentation.

Thank you

**Comment by ShantelPeters** [comment]
Is it okay if I tackle this?

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Michaelkingsdev** [comment]
I can handle this particular task.

**Comment by gregemax** [comment]
Can I jump on this task? I have strong experience in backend development with TypeScript and TypeORM, and I’m confident in implementing the described entities, CRUD APIs, and relationships. I’ll also ensure test coverage exceeds 80%.

**Comment by mimisavage** [comment]
Can I take this issue?

**Comment by NueloSE** [comment]
I'd be happy to do this.

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by jsanchez556** [comment]
Hi, I am José Mario, and I am a Senior Full-Stack Developer from Costa Rica, starting to love the development of Web3 and proficiency in an array of technologies such as JavaScript, TypeScript, Go, Python, Node.js, React, and C#. I love contributing to open-source projects. 
Currently learning Rust, Cairo, and dApp development. In the last few months, I have had the opportunity to work with projects involving Rust, Cairo, TypeScript, Git, and Docker, further developing my skill set.
My journey in the tech industry has been fueled by a love for learning and innovation. Since version 7.0, I’ve actively participated in ODHacks, driven by my work with Dojo Coding.

How to Approach the Solution:

1. Implement the entities Product, ProductType, and ProductVariant using TypeORM with appropriate relationships
2. Implement the controller for each entity with the following CRUD operations (Create, Read, Update, Delete)
3. Make sure that entity relationships are correctly enforced
4. Write tests for individual methods and for the full API flow, ensuring test coverage is above 80%

**Comment by Nityam573** [comment]
Can I take care of this issue?

**Comment by 1nonlypiece** [comment]
Let me try this one!

**Comment by Villarley** [comment]
hey @jimenezz22 
Task assigned to you. Let me know if you need further clarification or additional support!😊

Here is our telegram group, please join https://t.me/starshopcr
