### ISSUE TITLE
[BK]: Create Attributes, AttributeValues, and ProductVariantAttributes Entities and APIs

### ISSUE THREAD

**Issue by KevinLatino** [StarShopCr/StarShop-Backend#15]
> [!IMPORTANT]  
  Before applying, please read the [Contributors Guide](https://github.com/StarShopCr/contributors-guide). Following the guide increases your chances of being assigned to this task.  

**Description**: Implement `Attributes`, `AttributeValues`, and `ProductVariantAttributes` entities and their associated CRUD APIs.

#### Attribute
```typescript
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn } from 'typeorm';

@Entity('attributes')
export class Attribute {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @CreateDateColumn()
  createdAt: Date;
}
```

#### AttributeValue
```typescript
import { Entity, PrimaryGeneratedColumn, Column, ManyToOne, CreateDateColumn } from 'typeorm';
import { Attribute } from './Attribute';

@Entity('attribute_values')
export class AttributeValue {
  @PrimaryGeneratedColumn()
  id: number;

  @ManyToOne(() => Attribute)
  attribute: Attribute;

  @Column()
  value: string;

  @CreateDateColumn()
  createdAt: Date;
}
```

#### ProductVariantAttribute
```typescript
import { Entity, PrimaryGeneratedColumn, ManyToOne, CreateDateColumn } from 'typeorm';
import { ProductVariant } from './ProductVariant';
import { AttributeValue } from './AttributeValue';

@Entity('product_variant_attributes')
export class ProductVariantAttribute {
  @PrimaryGeneratedColumn()
  id: number;

  @ManyToOne(() => ProductVariant)
  productVariant: ProductVariant;

  @ManyToOne(() => AttributeValue)
  attributeValue: AttributeValue;

  @CreateDateColumn()
  createdAt: Date;
}
```

### Tasks
1. Define entities: `Attribute`, `AttributeValue`, and `ProductVariantAttribute`.
2. Create fully functional CRUD APIs for each entity.
3. Write comprehensive unit and integration tests.

### Acceptance Criteria
- APIs for CRUD operations work seamlessly.
- Relationships between entities are properly enforced.
- Test coverage >80%.

**Comment by Supa-mega** [comment]
May I handle this issue?

**Comment by Bosun-Josh121** [comment]
I am applying to this issue via OnlyDust platform.

My background and how it can be leveraged:

software engineering background, backend & smart contract dev with contribution to similar tasks(https://app.onlydust.com/u/Bosun-Josh121) looking to make first contribution on this project

How I plan on tackling this issue
I would define the stated entities & create CRUD apis for created entities with tests as stated. Would work on feedback & recommendation ensuring contact. Can deliver within a day upon assignment

**Comment by Shukazuby** [comment]
Hello, I am Zubaidat, a backend developer with expertise in TypeORM and building reliable CRUD APIs.

Plan to Solve the Issue:

I will define the Attribute, AttributeValue, and ProductVariantAttribute entities in TypeORM and implement fully functional CRUD APIs for each. Additionally, I will write comprehensive unit and integration tests to ensure each API is reliable and performs as expected.

ETA:
I estimate completing this task in 50hrs, including development, testing, and documentation.

Thank you

**Comment by ShantelPeters** [comment]
Could I be assigned to this?

**Comment by blessingbytes** [comment]
I’d like to work on this.

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Michaelkingsdev** [comment]
I can handle this particular task.

**Comment by gregemax** [comment]
Can I take this on? I have experience with backend development using TypeScript and TypeORM, and I’m confident in implementing the entities, relationships, and CRUD APIs as described. I’ll also ensure comprehensive test coverage above 80%.

**Comment by Ekene001** [comment]
Hello I'm Ekene, a frontend and blockchain developer with proficiency in Rust/solidity, Typescript, react/next js and typescript, and I’m excited about the opportunity to collaborate and bring my skills to the table. 

heres how i'll tackle this task: 

I will first design the database schema to establish the relationships between these entities. Once the schema is defined, I will create models for each entity in the backend. Then, I will develop the CRUD APIs for creating, reading, updating, and deleting records for these entities, ensuring they follow best practices and are properly validated. Finally, I will test the APIs thoroughly to confirm their functionality and consistency with the intended use cases.

**Comment by mimisavage** [comment]
Could I try solving this?

**Comment by jsanchez556** [comment]
Hi, I am José Mario, and I am a Senior Full-Stack Developer from Costa Rica, starting to love the development of Web3 and proficiency in an array of technologies such as JavaScript, TypeScript, Go, Python, Node.js, React, and C#. I love contributing to open-source projects. 
Currently learning Rust, Cairo, and dApp development. In the last few months, I have had the opportunity to work with projects involving Rust, Cairo, TypeScript, Git, and Docker, further developing my skill set.
My journey in the tech industry has been fueled by a love for learning and innovation. Since version 7.0, I’ve actively participated in ODHacks, driven by my work with Dojo Coding.

How to Approach the Solution: 

1. Implement entities Attribute, AttributeValue, and ProductVariantAttribute establishing appropriate relationships
2. Provide an implementation for each entity controller with the following CRUD operations: Create, Read, Update, Delete
3. Ensure proper entity relationships are enforced, such as between Attribute and AttributeValue, ProductVariant
4. Individual methods and full API flow test writing, test coverage should be more than 80%

**Comment by Superfly101** [comment]
Hello, I'm Daniel Ukoha a software engineer who's passionate about problem solving and building products to meet users' needs. This is my first ODHack and I can't wait to make my first contribution.

Here's how I'll tackle this issue:
1) I will create the three entities (Attribute, AttributeValue, ProductVariantAttribute) in src/entities/
2) Add their corresponding services in src/services/ with CRUD operations
3) Create DTOs for input validation in src/dto/
4) Implement controllers in src/controllers/ to expose CRUD endpoints
5) Write unit tests for services and integration tests for controllers

**Comment by 1nonlypiece** [comment]
I’m interested in this one.

**Comment by gregemax** [comment]
May I take this issue on? I have extensive experience in backend development with TypeScript and TypeORM. I can implement the Attribute, AttributeValue, and ProductVariantAttribute entities with properly enforced relationships, as well as develop fully functional CRUD APIs for each. I’ll also ensure comprehensive unit and integration tests with coverage exceeding 80%.

**Comment by BrunoAmbricca** [comment]
I’d love to work on this task.

**Comment by mariocodecr** [comment]
Hii! My name is Mario Araya, I’m a Software Developer with 2+ years of experience. I have worked with backend technologies such as Cairo, Java, and C#, as well as frontend development using React, NextJS, and JavaScript/TypeScript. I’ve made contributions to open-source projects, completed a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings, and participated in multiple hackathons. I’m also a member of the Dojo Coding community here in Costa Rica.


I will define the entities using the provided structure with typeorm decorators, ensuring relationships and constraints are accurately enforced, and update the database schema with necessary migrations. Develop services in a /services directory to handle database operations and controllers in a /controllers directory to manage API requests for creating, reading, updating, and deleting entities, registering routes in the main router file. Write comprehensive unit and integration tests using tools like Jest or Mocha, ensuring coverage exceeds 80% by testing successful operations, relationship enforcement, and edge cases. Validate functionality to confirm seamless CRUD operations and proper entity relationships, delivering a modular and scalable solution.

**Comment by suhas-sensei** [comment]
Gm, i am Suhas, having worked in previous 3 ODs, in issues involving ts, rust & cairo. Here's my approach to the issue concerned.
I will : 
> Create entity classes with TypeORM decorators for Attributes, AttributeValues, and ProductVariantAttributes, establishing proper relationships and validations
> Implement services for each entity with CRUD methods including proper error handling and relationship management
> Build controllers to expose RESTful endpoints for each entity's CRUD operations, with proper DTO validation and swagger documentation
> Set up repositories to handle database operations and complex queries, especially for the relationship between ProductVariants and AttributeValues
> Proper testing.

ETA : 2-3 days max

**Comment by ikezuby2012** [comment]
Hello, I'm a full-stack developer with nearly 4 years of experience working with JavaScript, TypeScript, C#, Express.js, and recently exploring Cairo for blockchain development. I’m passionate about building robust and scalable applications while ensuring clean and maintainable code.

For this issue, my approach would be:
Keep the implementation clean and organized:
Write the service logic in the src/service directory.
Implement the necessary DTOs for data transfer.
Controller Integration: Consume the service in the corresponding controller class for proper separation of concerns.
Validation: Create a validation class to verify inputs and ensure data integrity.
Testing: Write comprehensive unit tests to validate the functionality and ensure reliability.

ETA: 2-3 days

**Comment by olisaagbafor** [comment]
Hello StarShop Team,

I’m Olisa Agbafor, a skilled backend developer with over 5 years of experience building scalable APIs and managing database relationships using TypeORM and PostgreSQL. I’m excited to contribute to StarShop’s mission and would love to take on this issue.

My Approach:
Entity Definitions:

I will define the Attribute, AttributeValue, and ProductVariantAttribute entities with the required relationships and constraints, ensuring proper normalization and adherence to TypeORM standards.
CRUD APIs:

Develop and test RESTful endpoints for Create, Read, Update, and Delete operations for each entity.
Ensure robust validation and error handling at all stages.
Unit and Integration Tests:

Write comprehensive tests using Jest to ensure at least 80% code coverage, covering edge cases and relationship constraints.
ETA:
I estimate the work will be completed in 3 days, including testing and documentation.

Looking forward to your approval so I can start contributing. Thank you!

Best regards,
Olisa Agbafor

**Comment by khayss** [comment]
I'm a fullstack developer with high preference towards backend. I have worked on backends built with Rust and NodeJS. I understand the nature of work involves with a backend project.

For this issue, I'll:
- Define the required entities following the project structure.
- Create fully functional CRUD APIs to service each of this entities.
- Write tests to ensure the implementation works fully.
- Ensure these changes does not break the code base or affect any other sections.

I'll be glad to work on this issue.

**Comment by DuendexCR** [comment]
Let me try this one!

**Comment by caxtonacollins** [comment]
I am a Full Stack Developer with two years of professional experience, specializing in web3. I have strong background in blockchain and extensive experience in Next.js/React, TypeScript, Cairo and Rust.

To solve this, I'll first define entities using the provided typeORM models, setup the CRUD APIs for each entity. And finally test the api.

please assign me
ETA is 2days.

**Comment by Jagadeeshftw** [comment]
Could I try solving this?

**Comment by Ahmad940** [comment]
I’d like to resolve this, well experienced using express with typescript and orms like typeorm, prisma, sequalize and postgres/mysql
I will create the entities for each model in the "entities" folder, abstract the orm / db operations in a "repository" where all db/orm operations will be handled with try and catches to avoid unnecessary handling of these errors in the service directory where we will be calling the repository class and it functions, I will enforce zod typescript validation which have automatic type inference, and ensure the api request form data are what we are expecting and handle all potential errors to avoid the annoying internal server :), and mock tests to ensure are functionalities are in check and no funny bugs!

**Comment by Dorcas18** [comment]
Is it okay if I tackle this?

**Comment by ekumamatthew** [comment]
May I handle this issue?

**Comment by Joewizy** [comment]
Can I take care of this issue?

**Comment by BraCR10** [comment]
Hello maintainers I’m BRACR10 from the Dojo Coding community, I would like to contribute to this project.I’ll follow your instructions on defining entities, then I plan to create the corresponding routes for each entity to accomplish with the requirement of the CRUD APIs. I will also implement tests when necessary. ETA 1~3 days.

**Comment by sonkeydotcom** [comment]
I'd love to give this a go.

**Comment by kayceeDev** [comment]
My name is @kayceeDev,

I will tackle this issue using the TDD approach.
I will create the required entities and CRUD functionalities for each.
Using the TDD approach will make sure the solutions laigns perfectly with the required edge cases.
My experience in Nestjs and TypeScript will help me write efficient and scalable code. Thank you

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev
May I try my hand at this?
i would love to work on this and get it done

**Comment by vestor-dev** [comment]
May I handle this issue?
Would love to tackle this!
kindly assign :)

**Comment by Amarjeet325** [comment]
Hi , I am a full stack developer is a versatile professional skilled in both front-end and back-end development, capable of designing user interfaces, building robust server-side applications, and managing databases. 
Can I take this from here?  Thank you !

**Comment by Villarley** [comment]
hey @mariocodecr
Task assigned to you. Let me know if you need further clarification or additional support!😊

Here is our telegram group, please join https://t.me/starshopcr

**Comment by mariocodecr** [comment]
@KevinLatino thanks
