### ISSUE TITLE
[BK]: Create a Readme Called “Backend Rules”

### ISSUE THREAD

**Issue by Villarley** [StarShopCr/StarShop-Backend#16]
> [!IMPORTANT]  
  Before applying, please read the [Contributors Guide](https://github.com/StarShopCr/contributors-guide). Following the guide increases your chances of being assigned to this task.  
## Description
Develop a comprehensive `README.md` file to outline the rules and guidelines for contributing to the backend of the StarShop project. This document will ensure consistent development practices and facilitate collaboration among contributors.

## Tasks
1. **Introduction**: Add an overview of the backend rules and their purpose.
2. **Code Structure**: Detail the folder structure for controllers, services, models, routes, etc.
3. **Coding Standards**: Specify coding style guidelines (e.g., use of TypeScript, ESLint, Prettier).
4. **Pull Request Guidelines**: Provide instructions for creating and reviewing pull requests.
5. **Branching Strategy**: Define branch naming conventions and workflow (e.g., feature branches).
6. **Commit Message Guidelines**: Include rules for writing descriptive and standardized commit messages.
7. **Environment Setup**: Document the steps to configure the development environment (e.g., `.env` file usage, dependencies).
8. **Testing**: Outline the requirements for unit and integration tests, including tools like Jest.

## Expected Outcome
A `README.md` file located in the backend root directory that serves as a reference guide for all contributors. The document should be clear, well-structured, and adhere to Markdown standards.

**Comment by mimisavage** [comment]
Can I work on this, please?

**Comment by DanielVillatoro** [comment]
I have experience creating detailed documentation for backend projects. 
Assign this to me, and I’ll deliver a clear and structured README.md to guide contributors :)

**Comment by GideonBature** [comment]
Could I take a shot at this?

My name is Gideon Bature, a Software Engineer with experience building APIs with JavaScript/TypeScript. To write a comprehensive documentation, I will first of all study the code base to understand the structure and coding standards along with the Branching strategy, the commit message guidelines, environment setup and testing.

Next, I will also borrow somethings from the `Contributor's guide` to build a comprehensive `README.md` file for those coming to contribute to the project.

Thank you!

**Comment by Benjtalkshow** [comment]
I'd love to give this a go.

**Comment by Nityam573** [comment]
Could I take over this issue?
I am a beginner in open source this could help me a lot

**Comment by Villarley** [comment]
Hey @DanielVillatoro 
Task assigned to you. Let me know if you need further clarification or additional support!😊

Here is our telegram group, please join https://t.me/starshopcr
