### ISSUE TITLE
Create testing enviroment

### ISSUE THREAD

**Issue by aguilar1x** [StarShopCr/StarShop-Backend#3]
# Set Up Testing Framework for Backend API

## Objective
Establish a testing framework and infrastructure for the backend API built with Node.js, TypeScript, TypeORM, and Express. This will support unit and integration testing to ensure robust and reliable code quality.

---

## Description
This task involves configuring a dedicated testing environment for backend development. The setup should enable automated testing of:
- Service methods
- Database interactions
- API routes

The environment must include:
1. A testing framework.
2. An in-memory database or mocked database for tests.
3. Boilerplate utility functions for test setup and teardown.
4. Example test cases to validate the setup.

---

## Steps to Complete
1. **Install and Configure the Testing Framework**
   - Choose and install a testing framework (e.g., Jest or Mocha) along with required dependencies.
   - Use `ts-jest` or similar tools for TypeScript support.

   ```bash
   npm install --save-dev jest ts-jest supertest @types/jest @types/supertest
   ```

2. **Set Up TypeScript Testing Configuration**
   - Create a dedicated `tsconfig.test.json` for test builds.
   - Ensure compatibility with the testing framework and TypeScript project structure.

3. **Configure In-Memory Database**
   - Use SQLite or another lightweight in-memory database for isolated tests.
   - Create a test-specific TypeORM configuration file (e.g., `ormconfig.test.ts`).

4. **Develop Test Utilities**
   - Add utilities for initializing and tearing down the database during tests.
   - Example:
     ```typescript
     import { DataSource } from "typeorm";

     let testDataSource: DataSource;

     export const setupTestDB = async () => {
         testDataSource = new DataSource({
             type: "sqlite",
             database: ":memory:",
             synchronize: true,
             entities: ["src/entities/*.ts"]
         });
         await testDataSource.initialize();
     };

     export const teardownTestDB = async () => {
         if (testDataSource) await testDataSource.destroy();
     };
     ```

5. **Add Example Tests**
   - Write a basic unit test for a service function.
   - Create an integration test for an Express route using Supertest.

6. **Document the Testing Workflow**
   - Provide instructions for setting up and running tests locally.
   - Include commands for running tests and troubleshooting common issues.

7. **Integrate with CI/CD**
   - Ensure the CI/CD pipeline automatically runs the tests on every pull request.

---

## Acceptance Criteria
- A testing framework is fully configured and integrated with TypeScript.
- An in-memory database works for TypeORM during tests.
- Boilerplate setup and teardown functions are created for database tests.
- Example unit and integration tests pass successfully.
- The documentation guides developers to use the testing environment effectively.
- CI/CD pipeline executes tests reliably.

**Comment by Villarley** [comment]
@aguilar1x assign to me
